apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: che-endpoints-monitor
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
