apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-keycloak-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: che-endpoints-monitor
subjects:
- kind: ServiceAccount
  name: che-keycloak
  namespace: dev-tools
