apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: keycloak-log
  name: keycloak-log
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
